/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VideosIdRouteImport } from './routes/videos/$id'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'
import { Route as BlogNewRouteImport } from './routes/blog/new'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiEnvRouteImport } from './routes/api/env'
import { Route as UserUsernameBlogRouteImport } from './routes/user/$username/blog'
import { Route as QuizResultsShareTokenRouteImport } from './routes/quiz/results/$shareToken'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnvRoute = ApiEnvRouteImport.update({
  id: '/api/env',
  path: '/api/env',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameBlogRoute = UserUsernameBlogRouteImport.update({
  id: '/user/$username/blog',
  path: '/user/$username/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizResultsShareTokenRoute = QuizResultsShareTokenRouteImport.update({
  id: '/quiz/results/$shareToken',
  path: '/quiz/results/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/videos': typeof VideosRouteWithChildren
  '/api/env': typeof ApiEnvRoute
  '/api/test': typeof ApiTestRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/quiz/$id': typeof QuizIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quiz/results/$shareToken': typeof QuizResultsShareTokenRoute
  '/user/$username/blog': typeof UserUsernameBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/api/env': typeof ApiEnvRoute
  '/api/test': typeof ApiTestRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/quiz/$id': typeof QuizIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/videos': typeof VideosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quiz/results/$shareToken': typeof QuizResultsShareTokenRoute
  '/user/$username/blog': typeof UserUsernameBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/videos': typeof VideosRouteWithChildren
  '/api/env': typeof ApiEnvRoute
  '/api/test': typeof ApiTestRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/quiz/$id': typeof QuizIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quiz/results/$shareToken': typeof QuizResultsShareTokenRoute
  '/user/$username/blog': typeof UserUsernameBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/settings'
    | '/shop'
    | '/videos'
    | '/api/env'
    | '/api/test'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/blog/$slug'
    | '/blog/new'
    | '/quiz/$id'
    | '/videos/$id'
    | '/admin/'
    | '/blog/'
    | '/quiz/'
    | '/videos/'
    | '/api/auth/$'
    | '/quiz/results/$shareToken'
    | '/user/$username/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/settings'
    | '/shop'
    | '/api/env'
    | '/api/test'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/blog/$slug'
    | '/blog/new'
    | '/quiz/$id'
    | '/videos/$id'
    | '/admin'
    | '/blog'
    | '/quiz'
    | '/videos'
    | '/api/auth/$'
    | '/quiz/results/$shareToken'
    | '/user/$username/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/settings'
    | '/shop'
    | '/videos'
    | '/api/env'
    | '/api/test'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/blog/$slug'
    | '/blog/new'
    | '/quiz/$id'
    | '/videos/$id'
    | '/admin/'
    | '/blog/'
    | '/quiz/'
    | '/videos/'
    | '/api/auth/$'
    | '/quiz/results/$shareToken'
    | '/user/$username/blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  VideosRoute: typeof VideosRouteWithChildren
  ApiEnvRoute: typeof ApiEnvRoute
  ApiTestRoute: typeof ApiTestRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogNewRoute: typeof BlogNewRoute
  QuizIdRoute: typeof QuizIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  QuizResultsShareTokenRoute: typeof QuizResultsShareTokenRoute
  UserUsernameBlogRoute: typeof UserUsernameBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/env': {
      id: '/api/env'
      path: '/api/env'
      fullPath: '/api/env'
      preLoaderRoute: typeof ApiEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/blog': {
      id: '/user/$username/blog'
      path: '/user/$username/blog'
      fullPath: '/user/$username/blog'
      preLoaderRoute: typeof UserUsernameBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/results/$shareToken': {
      id: '/quiz/results/$shareToken'
      path: '/quiz/results/$shareToken'
      fullPath: '/quiz/results/$shareToken'
      preLoaderRoute: typeof QuizResultsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunityRoute: CommunityRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  VideosRoute: VideosRouteWithChildren,
  ApiEnvRoute: ApiEnvRoute,
  ApiTestRoute: ApiTestRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogNewRoute: BlogNewRoute,
  QuizIdRoute: QuizIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  QuizResultsShareTokenRoute: QuizResultsShareTokenRoute,
  UserUsernameBlogRoute: UserUsernameBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
